import { createContext } from 'react';

export const HelpLanguageContext = createContext('en');

// Help text is deliberately keyed by the visible English control label. The
// controls themselves, their values, and their saved settings never translate.
export const chineseHelp = {
  'Swap model': '选择换脸模型。各模型的身份保留、表情、遮挡和速度不同；换模型后先在预览中比较。缺少的模型会在首次使用时下载。',
  'Face selection': '决定处理首张检测到的脸、全部脸，或只处理已选定并匹配的人物。',
  'Detector engine': '选择人脸检测器。YOLOFace 可尝试侧脸和部分遮挡；RetinaFace R50 更适合近景；SCRFD 是原版默认。检测器只定位脸，不直接决定换脸身份。',
  'Face detection resolution': '检测前缩放图像的尺寸。提高可帮助小脸，但增加耗时和显存。',
  'Face detection threshold': '检测置信度阈值。降低可找回难检测的人脸，也会增加误检。',
  'Overlap NMS threshold': '重叠框抑制阈值。低值更容易合并近邻框；高值允许更多重叠的人脸框共存。',
  'Refine alignment (68-pt)': '使用 68 点关键点修正换脸对齐；侧脸可能更稳定，但会增加少量计算。',
  "🧩 Swap model's own face mask": 'HyperSwap 和 HifiFace 可输出自身的脸部区域遮罩；此项决定其参与最终贴合的程度，其他换脸模型不受影响。',
  'Rescue small faces': '对检测遗漏的小脸再尝试一次放大检测；会增加检测时间。',
  'Swapping steps': '同一张脸重复换脸的次数。更多次数可能加强身份，也可能带来失真；并非所有模型都会受益。',
  'Post-processing enhancer': '在换脸后进行清晰度和细节修复；可能同时改变身份与表情。',
  'Max face distance': '目标脸和已选参考脸的最大身份距离。放宽会匹配更多帧，也更容易错认他人。',
  'Subsample upscale': '换脸前的人脸裁剪尺寸。更大尺寸可能改善细节，但会增加计算量。',
  'AI upscale (after swap)': '换脸后对整段视频进行超分辨率处理，会明显增加输出时间。',
  'AI upscale model': '选择整段视频超分辨率所用的模型。',
  'Frame interpolation (after swap)': '在换脸后插入中间帧以提高帧率；会增加输出时间。',
  'Color/lighting match': '让换脸区域的颜色与目标画面的肤色和光照更接近。',
  'Enhancer Blend / Opacity': '控制增强结果的混合比例。降低可保留更多换脸前的外观。',
  'Skin detail transfer': '把目标脸的皮肤纹理混合回结果；提高可能更自然，也可能削弱源脸特征。',
  'Expression restore': '使用 LivePortrait 把目标帧表情重新施加到换脸结果；0 为关闭，约 0.8 可作为起点。需要本地表情模型，且不能同时开启完整旧版渲染兼容。',
  'Expression region': '选择表情恢复影响的面部范围。',
  'Face size': '调整换脸裁剪区域的大小；影响贴合与脸部边缘。',
  'Grain match': '让换脸区域的颗粒感贴近目标画面。',
  'Sharpen / soften': '调整换脸区域的锐度或柔和程度。',
  'Motion blur': '为换脸区域补充运动模糊，与原视频动态保持一致。',
  'Histogram match': '匹配换脸区域与目标画面的亮度和颜色分布。',
  'Degrade': '降低换脸区域的细节，以适配低质量原视频。',
  'Masking engine': '选择用于贴合或保护遮挡物的遮罩模型。不同模型对手、头发和物体的识别不同。',
  'Second masking engine (occlusion)': '再使用一个遮罩模型处理遮挡；可弥补单个模型遗漏，但会增加每张脸的计算。',
  'Objects to mask & restore': '输入要保留在换脸结果上方的物体类别，以逗号分隔。',
  'SAM2 checkpoint (speed ↔ quality)': '选择 SAM2 模型规模；较大的版本通常更精细，也更慢、更占显存。',
  'Show mask overlay in preview': '在预览中显示遮罩范围，便于检查遮挡和边缘。',
  'Offset face top': '调整脸部遮罩上边界。',
  'Offset face bottom': '调整脸部遮罩下边界。',
  'Offset face left': '调整脸部遮罩左边界。',
  'Offset face right': '调整脸部遮罩右边界。',
  'Face mask edge blend': '柔化脸部遮罩边缘，减少明显接缝。',
  'Mouth mask top': '调整原始嘴部恢复区域的上边界。',
  'Mouth mask bottom': '调整原始嘴部恢复区域的下边界。',
  'Mouth mask left': '调整原始嘴部恢复区域的左边界。',
  'Mouth mask right': '调整原始嘴部恢复区域的右边界。',
  'Mouth mask edge blend': '柔化嘴部恢复区域的边缘。',
  '3D source pose matching': '仅对图像源换脸模型提供匹配目标姿态的源脸裁剪；身份向量模型不受影响。',
  'Multi-angle source bank': '在多张源脸之间自动选择与当前目标姿态接近的源脸。',
  '↔️ Frontalize angled faces': '在换脸前暂时校正大角度侧脸，再转回原始角度；有助于降低极端角度失真。',
  'Frontalize above angle (°)': '超过此偏航或俯仰角度才启用正面化；阈值越低，触发越频繁。',
  'Reshape jaw/chin to source': '换脸后让下颌和下巴轮廓靠近源人物；幅度过大可能扭曲颈部边缘。',
  'Jaw reshape strength': '0 表示保持目标下颌，1 表示尽量采用源脸下颌。',
  'Video method': '选择视频的读取、处理与导出流程。某些时序功能只支持内存处理。',
  'On no face detected': '决定某帧未检测到人脸时如何处理；保留原帧可避免误换。',
  'Temporal detection (anti-flicker)': '先跟踪整段视频的人脸，利用前后帧补全短暂漏检并稳定身份。',
  'VR mode': '针对双眼立体视频调整处理方式。',
  'Reduce enhancer flicker': '对连续帧增强结果进行平滑，减轻亮度与细节闪烁。',
  'Flicker reduction strength': '值越高，增强结果在相邻帧之间越平滑。',
  'Temporal Smooth Strength': '平滑视频中人脸关键点及遮罩边缘；过高可能造成动作拖尾。',
  'Auto rotate horizontal faces': '尝试旋转横倒的人脸进行检测和处理。',
  'Skip audio': '导出视频时不附带原声音轨。',
  'Keep frames (when extracting)': '使用逐帧提取处理时保留中间帧文件。',
  'Wait before creating video': '处理帧结束后等待确认，再合成为最终视频。',
  'Lock face identities (video)': '在视频中追踪所选人物，减少转身或交叉时的身份切换。',
  'Stabilize face (video)': '平滑连续帧的脸部关键点，减少换脸区域抖动。',
  'Smoothing method': 'One Euro 会随动作速度调整平滑程度；EMA 使用固定平滑。',
  'Smoothing (min cutoff)': '数值越低越平滑，但快速动作可能更滞后。',
  'Reactivity (beta)': '数值越高，平滑器对快速动作的反应越快。',
  'Restore original mouth area': '把目标视频的原嘴部区域融合回换脸结果，以保留说话动作。',
  'Lip-sync (MuseTalk)': '根据音轨重新生成嘴型；与恢复原始嘴部互斥。',
  'Lip-sync audio source': '选择嘴型同步所用的原视频音轨或另行上传的音轨。',
  'Restore original eyes': '把目标视频的眼睛细节融合回换脸结果；可能降低源脸眼形相似度。',
  'Eyes blend amount': '原始目标眼睛混合回结果的比例。',
  'Eyes feather': '眼部恢复区域的边缘柔化程度。',
  'Eyes region size': '同时缩放双眼的恢复区域。',
  'Eyes width': '单独调整眼部恢复区域的宽度。',
  'Eyes height': '单独调整眼部恢复区域的高度。',
  'CodeFormer fidelity weight': '平衡细节修复与身份保持；更高通常更贴近输入脸。',
  'Align crop for the enhancer': '在增强前按修复模型训练时的方式重新对齐人脸裁剪。',
  'Re-match colour after enhancing': '增强后再次匹配肤色与光照，抵消增强模型引入的颜色变化。',
  'Provider': '推理后端。修改后需要重启应用才能生效。',
  'Precision mode (TensorRT)': 'TensorRT 的计算精度；低精度通常更快并节省显存。修改后重启生效。',
  'Force CPU for face analyser': '把人脸检测移到 CPU；较慢，但可绕过 GPU 检测异常。部分检测器需要重启才切换。',
  'Auto thread selection': '根据硬件基准和工作负载自动选择线程数。',
  'Max threads': '手动限制并行工作线程数；自动模式下不使用该值。',
  'Max memory (GB)': '内存上限；0 表示不限制。',
  'Swapper TRT pool': '换脸模型的 TensorRT 并发上下文数；提高会增加显存占用。',
  'Detect/Mask pool': '检测与遮罩的并发上下文数；提高可能加快处理，也会明显增加显存占用。',
  'Detector pool': '独立检测器的并发实例数；与检测/遮罩池不同。显存不足时应降低。',
  'Expression pool': '表情恢复模型的并发上下文数；仅在启用表情恢复时占用资源。',
  'NVENC preset': '硬件编码速度与压缩效率的平衡；较高预设会花更多编码时间。',
  'Encoder preset': '软件编码速度与文件大小的平衡。',
  'GPU video decode (NVDEC)': '使用 GPU 视频解码；自动模式会先检测是否可用，失败时回退 CPU。',
  'Batched swap': '将多张脸合并成一次 GPU 批量推理。',
  'Stage profiling (terminal)': '在终端显示各处理阶段的耗时，便于定位性能瓶颈。',
  'Video format': '选择输出容器；只显示当前 FFmpeg 支持的格式。',
  'Video codec': '选择与当前输出容器兼容的编码器。',
  'Video quality (cq)': '硬件编码的画质参数；数值越低通常画质越高、文件越大。',
  'Video quality (crf)': '软件编码的恒定质量参数；数值越低通常画质越高、文件越大。',
  'Stream to virtual camera (OBS)': '把实时换脸画面发布为系统虚拟摄像头。',
  'Server name': '留空时仅在本机访问。',
  'Server port': '0 表示使用默认端口。',
  'Filename output template': '使用 {file}、{time}、{date}、{i} 和 {timestamp} 组合输出文件名。',
  'Faceset library folder': '已保存 faceset 的目录。留空使用 app/facesets；也可指向本地同步目录。',
  'Follow system light / dark': '根据操作系统的明暗外观自动切换对应主题。',
  'Restore faces on add': '保存前使用 GFPGAN 修复模糊或压缩严重的参考脸。',
  'Quality gate': '只保留高于指定质量阈值的参考脸。',
  'Frame': '当前选中的视频帧与总帧数。',
};
