// A: roop-unleashed 4.4.0, matched to the user's 256px / DFL XSeg settings.
// Explicitly neutralise C-only processing; never capture machine/server/theme
// settings. Selects the separately validated A compatibility rendering path.
export const A_DEFAULT_SNAPSHOT = {
  id: 'builtin-a-default-v2',
  name: 'roop-unleashed-main comparison · 256px / XSeg / 1 step',
  settings: {
    a_compatibility_mode: true,
    source_identity_mode: 'average',
    a_mask_erosion: 1,
    a_mask_blur: 15,
    swap_model: 'inswapper',
    face_detection_mode: 'First found',
    detector_engine: 'scrfd',
    face_detector_size: '640',
    default_det_size: true,
    face_detector_threshold: 0.5,
    face_detector_nms: 0.4,
    refine_landmarks: false,
    temporal_roi_hint: false,
    rescue_small_faces: false,
    swap_model_mask_strength: 0,
    num_swap_steps: 1,
    selected_enhancer: 'None',
    enhancer_type: 'none',
    enhancer_blend: 0.65,
    blend_ratio: 0.65,
    codeformer_fidelity: 0.5,
    max_face_distance: 0.65,
    subsample_upscale: '256px',
    upscale_after_swap: false,
    upscale_model_after: 'esrganx2',
    interp_after_swap: 'off',
    color_transfer_mode: 'none',
    mask_engine: 'DFL XSeg',
    mask_engine_2: 'None',
    mask_clip_text: 'cup,hands,hair,banana,leg',
    sam2_model_size: 'tiny',
    show_mask_offsets: false,
    mask_top: 0,
    mask_bottom: 0,
    mask_left: 0,
    mask_right: 0,
    // C's ordinary mask blend remains available when compatibility is disabled.
    face_mask_blend: 20,
    mouth_top_scale: 1,
    mouth_bottom_scale: 1,
    mouth_left_scale: 1,
    mouth_right_scale: 1,
    mouth_mask_blend: 10,
    use_3d_recon: false,
    use_source_bank: false,
    use_frontalization: false,
    frontalization_threshold: 30,
    jaw_reshape: false,
    jaw_reshape_strength: 0,
    detail_transfer_strength: 0,
    merger_hist_match: 0,
    merger_sharpen: 0,
    merger_motion_blur: 0,
    merger_grain_match: 0,
    merger_degrade: 0,
    output_face_scale: 0,
    expression_restore_strength: 0,
    expression_restore_region: 'all',
    video_swapping_method: 'In-Memory processing',
    no_face_action: 'Use untouched original frame',
    temporal_detection: false,
    vr_mode: false,
    stabilize_enhancer: false,
    stabilize_enhancer_strength: 0,
    // This also controls a smoother independent of stabilize_face.
    temporal_smooth_strength: 0,
    autorotate_faces: true,
    skip_audio: false,
    keep_frames: false,
    wait_after_extraction: false,
    track_identities: false,
    stabilize_face: false,
    stabilize_method: 'one_euro',
    stabilize_min_cutoff: 0.05,
    stabilize_beta: 0.02,
    restore_original_mouth: false,
    restore_original_eyes: false,
    eyes_blend_amount: 1,
    eyes_feather_blend: 25,
    eyes_size_factor: 1,
    eyes_radius_x: 1,
    eyes_radius_y: 1,
    parser_regions: ['skin', 'brows', 'eyes', 'nose', 'mouth'],
    parser_region_grow: {},
    enhancer_align: false,
    color_match_after_enhance: false,
    lipsync_enabled: false,
    lipsync_audio_source: 'original',
    lipsync_audio_path: null,
    output_method: 'File',
  },
};
